# Application
spring.application.name=api-gateway
server.port=8080

# Eureka - gateway juga daftar ke eureka + tanya alamat service dari sini
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ===== ROUTING - BUSINESS =====
# lb:// = load-balanced: tanya Eureka alamat service, bukan hardcode port

# Rute 0: /api/auth/** → auth-service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# Rute 1: /api/users/** → user-service
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://user-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**

# Rute 2: /api/products/** → product-service
spring.cloud.gateway.routes[2].id=product-service
spring.cloud.gateway.routes[2].uri=lb://product-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/products/**

# ===== ROUTING - API DOCS =====
# /docs/specs/xxx → /v3/api-docs milik tiap service (SetPath = tulis ulang path)

# Rute 3: spec auth-service
spring.cloud.gateway.routes[3].id=auth-service-docs
spring.cloud.gateway.routes[3].uri=lb://auth-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/docs/specs/auth
spring.cloud.gateway.routes[3].filters[0]=SetPath=/v3/api-docs

# Rute 4: spec user-service
spring.cloud.gateway.routes[4].id=user-service-docs
spring.cloud.gateway.routes[4].uri=lb://user-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/docs/specs/users
spring.cloud.gateway.routes[4].filters[0]=SetPath=/v3/api-docs

# Rute 5: spec product-service
spring.cloud.gateway.routes[5].id=product-service-docs
spring.cloud.gateway.routes[5].uri=lb://product-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/docs/specs/products
spring.cloud.gateway.routes[5].filters[0]=SetPath=/v3/api-docs

# Actuator
management.endpoints.web.exposure.include=health,info
