spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.default_schema=order_service
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true
eureka.client.service-url.defaultZone=${EUREKA_URL}
