spring.application.name=config-server
server.port=8888

# Mode native = baca config dari folder lokal (bukan git repo)
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:///${user.dir}/../config-repo
